""" Add support for user groups etc.

Revision ID: 0d730fab328a
Revises: e47a91921333
Create Date: 2016-09-28 12:31:14.218560

"""

# revision identifiers, used by Alembic.
revision = '0d730fab328a'
down_revision = 'e47a91921333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_join_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('blueprint_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('plugin', sa.String(length=32), nullable=True),
    sa.Column('blueprint_schema', sa.Text(), nullable=True),
    sa.Column('blueprint_form', sa.Text(), nullable=True),
    sa.Column('blueprint_model', sa.Text(), nullable=True),
    sa.Column('allowed_attrs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plugin'], ['plugins.id'], name=op.f('fk_blueprint_templates_plugin_plugins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_templates'))
    )
    op.create_table('groups_banned_users',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_banned_users_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_banned_users_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_groups_banned_users'))
    )
    op.create_table('groups_owners',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_owners_group_id_groups')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_groups_owners_owner_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'owner_id', name=op.f('pk_groups_owners'))
    )
    op.create_table('groups_users',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_users_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_users_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_groups_users'))
    )
    with op.batch_alter_table(u'blueprints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.String(length=32), nullable=True))
        batch_op.drop_constraint(u'fk_blueprints_plugin_plugins', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_blueprints_template_id_blueprint_templates'), 'blueprint_templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_blueprints_group_id_groups'), 'groups', ['group_id'], ['id'])
        batch_op.drop_column('plugin')

    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group_owner', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.drop_column('is_group_owner')

    with op.batch_alter_table(u'blueprints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plugin', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_blueprints_group_id_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_blueprints_template_id_blueprint_templates'), type_='foreignkey')
        batch_op.create_foreign_key(u'fk_blueprints_plugin_plugins', 'plugins', ['plugin'], ['id'])
        batch_op.drop_column('template_id')
        batch_op.drop_column('group_id')

    op.drop_table('groups_users')
    op.drop_table('groups_owners')
    op.drop_table('groups_banned_users')
    op.drop_table('blueprint_templates')
    op.drop_table('groups')
    ### end Alembic commands ###
